[keyboard]
name = "rmk-horizon"
product_name = "rmk-horizon"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "lemon"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_04", "P1_06", "P0_10", "P0_09"]
output_pins = ["P0_06", "P0_08", "P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11", "P1_11", "P1_13", "P1_15", "P0_02", "P0_29", "P0_31"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation.
# Checkout doc here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
# row2col = true

[layout]
rows = 4
cols = 14
layers = 4
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5)             (0,8) (0,9) (0,10) (0,11) (0,12) (0,13)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5)             (1,8) (1,9) (1,10) (1,11) (1,12) (1,13)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9) (2,10) (2,11) (2,12) (2,13)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (3,8) (3,9) (3,10) (3,11) (3,12) (3,13)
"""

[aliases]
upper = "MO(upper)"
lower = "MO(lower)"
tild = "SHIFTED(Grave)"
exlm = "SHIFTED(Kc1)"
at = "SHIFTED(Kc2)"
hash = "SHIFTED(Kc3)"
dlr = "SHIFTED(Kc4)"
perc = "SHIFTED(Kc5)"
circ = "SHIFTED(Kc6)"
ampr = "SHIFTED(Kc7)"
astr = "SHIFTED(Kc8)"
lprn = "SHIFTED(Kc9)"
rprn = "SHIFTED(Kc0)"
unds = "SHIFTED(Minus)"
plus = "SHIFTED(Equal)"
lcbr = "SHIFTED(LeftBracket)"
rcbr = "SHIFTED(RightBracket)"
pipe = "SHIFTED(Backslash)"
bt0 = "User0"
bt1 = "User1"
bt2 = "User2"
btnext = "User3"
btprev = "User4"
btclr = "User5"
usbble = "User6"

[[layer]]
name = "base"
keys = """
Tab    Q     W    E    R      T                   Y     U      I     O    P         Backspace
Escape A     S    D    F      G                   H     J      K     L    Semicolon Quote
LShift Z     X    C    V      B     Home PageUp   N     M      Comma Dot  Slash     Enter
RShift LCtrl LAlt LGui @upper Space End  PageDown Space @lower Left  Down Up        Right
"""

[[layer]]
name = "upper"
keys = """
@tild  @exlm @at @hash @dlr @perc     @circ @ampr @astr @lprn @rprn _
Delete F1    F2  F3    F4   F5        F6    @unds @plus @lcbr @rcbr @pipe
_      F7    F8  F9    F10  F11   _ _ F12   No    No    Home  End   _
_      _     _   _     _    _     _ _ _     _     MediaNextTrack AudioVolDown AudioVolUp MediaPlayPause
"""

[[layer]]
name = "lower"
keys = """
Grave  Kc1 Kc2 Kc3 Kc4 Kc5     Kc6 Kc7   Kc8    Kc9         Kc0          _
Delete F1  F2  F3  F4  F5      F6  Minus Equal  LeftBracket RightBracket Backslash
_      F7  F8  F9  F10 F11 _ _ F12 No    No     PageUp      PageDown     _
_      _   _   _   _   _   _ _ _   _     MediaNextTrack AudioVolDown AudioVolUp MediaPlayPause
"""

[[layer]]
name = "adjust"
keys = """
_ @bt0 @bt1 @bt2 _ _                 _ _ _ _ _ _
_ _    _    _    _ _                 _ _ _ _ _ _
_ _    _    _    _ _ @btclr  @btprev _ _ _ _ _ _
_ _    _    _    _ _ @usbble @btnext _ _ _ _ _ _
"""

[behavior]
tri_layer = { upper = 1, lower = 2, adjust = 3 }
one_shot = { timeout = "1s" }

[ble]
enabled = true
# vddh has an internal voltage divider
# battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806

# charge_state.pin = "P0_25"
# charge_state.low_active = false
# charge_led.pin = "P0_29"
# charge_led.low_active = false
